version: "3.8"

services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - /bin/sh
      - -c
      - |
        redpanda start \
          --overprovisioned \
          --smp 1 \
          --memory 1G \
          --reserve-memory 0M \
          --node-id 0 \
          --check=false \
          --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092 \
          --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
    ports:
      - "19092:19092"
      - "9092:9092"
      - "9644:9644"

  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin
    ports:
      - "9200:9200"
      - "9600:9600"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
    ports:
      - "5601:5601"
    depends_on: [opensearch]

  unleash-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: unleash
      POSTGRES_DB: unleash
      POSTGRES_USER: unleash
    ports: ["5542:5432"]

  unleash:
    image: unleashorg/unleash-server:latest
    environment:
      DATABASE_URL: postgres://unleash:unleash@unleash-db:5432/unleash
      LOG_LEVEL: info
      INIT_ADMIN_API_TOKENS: default:dev.token
    ports: ["4242:4242"]
    depends_on: [unleash-db]

  unleash-proxy:
    image: unleashorg/unleash-proxy:latest
    environment:
      UNLEASH_PROXY_URL: http://unleash:4242/api
      UNLEASH_URL: http://unleash:4242/api
      UNLEASH_API_TOKEN: default:dev.token
      UNLEASH_PROXY_CLIENT_KEYS: frontend.dev.key
      LOG_LEVEL: info
    ports: ["4243:4243"]
    depends_on: [unleash]

  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_LOG_LEVEL: notice
    volumes:
      - ./kong/kong.yml:/kong/kong.yml:ro
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on: []

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ["9090:9090"]

  grafana:
    image: grafana/grafana:latest
    ports: ["3002:3000"]
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"

  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=lambda,apigateway,s3,iam
      - EDGE_PORT=4566
      - DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - "localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  localstack: